version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  backend:
    env_file: .backend.env
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5984:5984"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=rag_db
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
      - ./db:/app/db
    networks:
      - app_network

  frontend:
    env_file: .frontend.env
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:5984
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data: